version: '1.0'

name: spams-container
services:
  bot:
    env_file:
      - ./telegram-bot/.env
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    container_name: telegram-bot-container
    restart: always
    environment:
      - HOST_URL=http://web-spams-container:8080
      - BOT_TOKEN=7772483926:AAFkT_nibrVHwZmlJajxbXRU4Wxe_b7t_RI